apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - payment_orchestrator.yml
  - orchestrator-ingress.yaml
  - orchestrator-service.yaml
images:
  - name: paymentorchestrator
    newName: httpsantos/slip_service
    newTag: "2.3"